export const stringsCalendar = {
  addMatch: 'Dodaj mecz',
  common: {
    noneOption: '— brak —',
  },
  createeditMatchFieldsLabels: {
    awayGKIds: 'Bramkarze gości (opcjonalnie)',
    awayTeam: 'Goście (opcjonalnie)',
    date: 'Data i godzina',
    group: 'Grupa (opcjonalnie)',
    homeGKIds: 'Bramkarze gospodarzy (opcjonalnie)',
    homeTeam: 'Gospodarze (opcjonalnie)',
    index: 'Index w rundzie (opcjonalnie)',
    round: 'Runda (opcjonalnie)',
    scoreAway: 'Wynik gości (opcjonalnie)',
    scoreHome: 'Wynik gospodarzy (opcjonalnie)',
    stage: 'Etap turnieju',
    status: 'Status (opcjonalnie)',
    statusOptions: {
      FINISHED: 'Zakończony',
      LIVE: 'Na żywo',
      SCHEDULED: 'Zaplanowany',
    },
  },
  deleteAllMatches: 'Usuń wszystkie mecze',
  deleteAllMatchesByGroup: 'Usuń wszystkie mecze z fazy grupowej',
  deleteMatch: 'Usuń mecz',
  deleteModalLabels: {
    cancel: 'Anuluj',
    confirm: 'Usuń',
  },
  editMatch: 'Edytuj mecz',
  generateMatches: 'Wygeneruj terminarz',
  generateMatchesTitleForm: 'Wygeneruj terminarz algorytmem Round Robin',
  generateRoundRobinFieldsFormLabels: {
    clearExisting: 'Wyczyść istniejące mecze (opcjonalnie)',
    dayInterval: 'Odstęp dni między rundami (opcjonalnie)',
    doubleRound: 'Mecz i rewanż (opcjonalnie)',
    firstMatchTime: 'Godzina pierwszego meczu (opcjonalnie)',
    groupIds: 'Grupy do wygenerowania',
    matchIntervalMinutes: 'Interwał między meczami (min) (opcjonalnie)',
    matchTimes: {
      addHour: 'Dodaj godzinę',
      fieldTime: 'HH:MM (opcjonalnie)',
      hour: 'Godzina',
      label: 'Godziny meczów (alternatywa dla interwału)',
      remove: 'Usuń',
    },
    roundInSingleDay: 'Cała runda jednego dnia',
    shuffleTeams: 'Potasuj drużyny przed losowaniem (opcjonalnie)',
    startDate: 'Data startu',
    yesNoOptions: {
      no: 'Nie',
      yes: 'Tak',
    },
  },
  headerTitle: 'Terminarz rozgrywek',
  matchEvents: 'Zdarzenia meczowe (opcjonalnie)',
  matchEventsFormLabels: {
    addEvent: 'Dodaj zdarzenie',
    card: 'Rodzaj kartki (opcjonalnie)',
    cardOptions: {
      RED: 'Czerwona',
      SECOND_YELLOW: 'Druga żółta',
      YELLOW: 'Żółta',
    },
    event: 'Zdarzenie',
    id: 'Id',
    minute: 'Minuta (opcjonalnie)',
    playerId: 'Zawodnik',
    removeEvent: 'Usuń zdarzenie',
    teamId: 'Drużyna zdarzenia',
    type: 'Typ zdarzenia',
    typeOptions: {
      ASSIST: 'Asysta',
      CARD: 'Kartka',
      GOAL: 'Gol',
      OWN_GOAL: 'Bramka samobójcza',
    },
  },
};
