export const stringsCalendar = {
  addMatch: 'Dodaj mecz',
  common: {
    noneOption: '— brak —',
  },
  createeditMatchFieldsLabels: {
    awayGKIds: 'Bramkarze gości',
    awayTeam: 'Goście',
    date: 'Data i godzina',
    group: 'Grupa',
    homeGKIds: 'Bramkarze gospodarzy',
    homeTeam: 'Gospodarze',
    index: 'Index w rundzie',
    round: 'Runda',
    scoreAway: 'Wynik gości',
    scoreHome: 'Wynik gospodarzy',
    stage: 'Etap turnieju',
    status: 'Status',
    statusOptions: {
      FINISHED: 'Zakończony',
      LIVE: 'Na żywo',
      SCHEDULED: 'Zaplanowany',
    },
  },
  deleteAllMatches: 'Usuń wszystkie mecze',
  deleteAllMatchesByGroup: 'Usuń wszystkie mecze z fazy grupowej',
  deleteMatch: 'Usuń mecz',
  deleteModalLabels: {
    cancel: 'Anuluj',
    confirm: 'Usuń',
  },
  editMatch: 'Edytuj mecz',
  generateMatches: 'Wygeneruj terminarz',
  generateMatchesTitleForm: 'Wygeneruj terminarz algorytmem Round Robin',
  generateRoundRobinFieldsFormLabels: {
    clearExisting: 'Wyczyść istniejące mecze w tych grupach',
    dayInterval: 'Co ile dni nowa kolejka',
    doubleRound: 'Mecz i rewanż',
    firstMatchTime: 'Godzina pierwszego meczu (gdy używamy interwału)',
    groupIds: 'Grupy do wygenerowania',
    matchIntervalMinutes: 'Interwał minut między meczami (opcjonalnie)',
    matchTimes: {
      addHour: 'Dodaj godzinę',
      fieldTime: 'HH:mm',
      hour: 'Godzina',
      label: 'Godziny w dniu kolejki (HH:mm)',
      remove: 'Usuń',
    },
    roundInSingleDay: 'Cała kolejka jednego dnia',
    shuffleTeams: 'Potasuj drużyny przed losowaniem',
    startDate: 'Data startu',
    yesNoOptions: {
      no: 'Nie',
      yes: 'Tak',
    },
  },
  headerTitle: 'Terminarz rozgrywek',
  matchEvents: 'Zdarzenia meczowe',
  matchEventsFormLabels: {
    addEvent: 'Dodaj zdarzenie',
    card: 'Rodzaj kartki',
    cardOptions: {
      RED: 'Czerwona',
      SECOND_YELLOW: 'Druga żółta',
      YELLOW: 'Żółta',
    },
    event: 'Zdarzenie',
    id: 'Id',
    minute: 'Minuta',
    playerId: 'Zawodnik',
    removeEvent: 'Usuń zdarzenie',
    teamId: 'Drużyna zdarzenia',
    type: 'Typ zdarzenia',
    typeOptions: {
      ASSIST: 'Asysta',
      CARD: 'Kartka',
      GOAL: 'Gol',
      OWN_GOAL: 'Bramka samobójcza',
    },
  },
};
