export const stringsMatchDetails = {
  modalTitle: 'Szczegóły meczu',
  headerAriaClose: 'Zamknij modal ze szczegółami meczu',
  close: 'Zamknij',
  group: 'Grupa',
  noEvents: 'Brak zdarzeń',
  minuteSuffix: '’',
  scorerIconLabel: 'Strzelec bramki',
  ownGoal: 'Gol samobójczy',
  penalty: 'Rzut karny',
  details: 'Szczegóły meczu',
  vote: 'Zagłosuj',
  vote_2: 'Głosuj na MVP',
  load_voting: 'Ładowanie głosowania…',
  voting_NOT_STARTED: 'Głosowanie ruszy po zakończeniu meczu',
  voting_CLOSED: 'Głosowanie zakończone',
  hasVoted: 'Twój głos został zapisany. Dziękujemy!',
  actual_votes: 'Aktualne głosy:',
  player: 'Zawodnik',
  team: 'Drużyna',
  votes: 'Głosy',
  noVotes: 'Brak oddanych głosów',
  votingResults: 'Wyniki głosowania',
  closed: 'Zamknięte:',
  winner: 'Zwycięzca',
  endVoting: ' Koniec głosowania za:',
  editMatch: 'Edytuj mecz',
  deleteMatch: 'Usuń mecz',
};
